#!/usr/bin/env bash

calculate_new_grade() {
    echo "something"
}

recalculate_grade() {
    echo "another something"
}

read_grades() {
    while IFS= read -r line; do
        echo "$line"
    done < saved_data.txt
}

clear_grades() {
    while IFS= read -r line; do
        echo "" >> saved_data.txt
    done < saved_data.txt
    echo "File cleared"
}

echo -e "\nSelect from one of the following options:"
echo "  [0] Calculate new grade"
echo "  [1] Recalculate pre-existing grade"
echo "  [2] Read pre-existing grades"
echo "  [3] Clear all grades"
echo "  [x] Exit"
echo -n "User Input: "
read user_option

while : ; do    # do while user_option != "x"
    case $user_option in
    0)    # Calculating new grade
        echo "Calculating new grade"
        ;;
    1)    # Recalculating pre-existing grades
        echo "Recalculating pre-existing grade"
        ;;
    2)    # Reading previous grades
        read_grades | less
        ;;
    3)    # Clearing all grades
        echo -n "Type CLEAR to confirm or [x] to exit: "
        read user_choice
        while : ; do
            case $user_choice in
                CLEAR)
                    echo "Clearing file"
                    clear_grades
                    ;;
                x)
                    echo "Exiting..."
                    ;;
                *)
                    echo "Invalid option"
                    ;;
             esac
             [[ user_choice == "x" ]] || break
        done
        ;;
    x)    # Exiting
        echo -e "\nExiting..."
        ;;
    *)    # default, if option given is invalid
        echo "Invalid option, please try again"
        ;;
    esac
    [[ user_option == "x" ]] || break
done      
echo ""